<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <OutputType>Library</OutputType>
    <AssemblyName>OverWolf.Client.Core</AssemblyName>
    <RootNamespace>OverWolf.Client.Core</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
</Project>
